---
title: "Müge Çetinkaya's Resume"
author: "Müge Çetinkaya"
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/105QMOQQd_eqK5RtstHvk8k7o5gHwY3kshMQFbUrbZ1M",  
  pdf_mode = params$pdf_mode
)
```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```

```{r results="asis", eval=FALSE}
if(params$pdf_mode){
  cat("View this CV online with links at _muge.fr/resume_")
} else {
  cat("<i class='fas fa-download'></i> <a href='https://iowio.github.io/resume/muge-cetinkaya.pdf'>Download PDF</a>")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Language Skills {#languageskills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars(skill_type = "language")
```

Software Skills {#softwareskills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars(skill_type = "software")
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

The source code for this resume is available [on github.com/iowio/resume](https://github.com/iowio/resume).


Main
================================================================================

MÜGE ÇETİNKAYA {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```


Work Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('industy_experience_aside')
```
:::

```{r}
CV %<>% print_section('industry_positions')
```


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```